import * as anchor from '@coral-xyz/anchor';
import { Connection, PublicKey, clusterApiUrl } from '@solana/web3.js';
import type { Wallet } from '@solana/wallet-adapter-react';

// Load program ID from env (set after deployment) – safe lazy init
const PROGRAM_ID_STR = process.env.SOLANA_PROGRAM_ID;
const PROGRAM_ID = PROGRAM_ID_STR ? new PublicKey(PROGRAM_ID_STR) : null as unknown as PublicKey;

// RPC endpoint – default to devnet if not provided
const RPC_URL = process.env.SOLANA_RPC_URL || clusterApiUrl('devnet');

/**
 * Returns an Anchor Provider connected to the Solana devnet (or custom RPC).
 * The wallet argument should be a connected wallet adapter instance.
 */
export function getProvider(wallet: Wallet) {
    const connection = new Connection(RPC_URL, 'processed');
    const provider = new anchor.AnchorProvider(connection, wallet as unknown as anchor.Wallet, {
        preflightCommitment: 'processed',
        commitment: 'processed',
    });
    return provider;
}

/** Load the Anchor program interface (IDL) generated by `anchor build`.
 * In a real project you would import the JSON file generated under `target/idl/ante_poker.json`.
 * For this skeleton we provide a minimal inline IDL sufficient for the four instructions.
 */
const IDL = {
    version: '0.1.0',
    name: 'ante_poker',
    instructions: [
        {
            name: 'initializeGame',
            accounts: [
                { name: 'game', isMut: true, isSigner: false },
                { name: 'authority', isMut: true, isSigner: true },
                { name: 'systemProgram', isMut: false, isSigner: false },
            ],
            args: [
                { name: 'bigBlind', type: 'u64' },
                { name: 'maxPlayers', type: 'u8' },
            ],
        },
        {
            name: 'joinGame',
            accounts: [
                { name: 'game', isMut: true, isSigner: false },
                { name: 'player', isMut: true, isSigner: true },
                { name: 'playerTokenAccount', isMut: true, isSigner: false },
                { name: 'gameTokenAccount', isMut: true, isSigner: false },
                { name: 'tokenProgram', isMut: false, isSigner: false },
            ],
            args: [{ name: 'buyInAmount', type: 'u64' }],
        },
        {
            name: 'requestShuffle',
            accounts: [
                { name: 'game', isMut: true, isSigner: false },
                { name: 'authority', isMut: true, isSigner: true },
            ],
            args: [],
        },
        {
            name: 'distributePot',
            accounts: [
                { name: 'game', isMut: true, isSigner: false },
                { name: 'authority', isMut: true, isSigner: true },
                { name: 'gameTokenAccount', isMut: true, isSigner: false },
                { name: 'tokenProgram', isMut: false, isSigner: false },
            ],
            args: [{ name: 'winnerIndices', type: { vec: 'u8' } }],
        },
    ],
} as const;

function getProgram(provider: anchor.Provider) {
    if (!PROGRAM_ID) throw new Error('SOLANA_PROGRAM_ID is not set');
    return new (anchor.Program as any)(IDL as any, PROGRAM_ID, provider);
}

/** Initialize a new game on-chain */
export async function initializeGame(
    wallet: Wallet,
    bigBlind: number,
    maxPlayers: number,
) {
    const provider = getProvider(wallet);
    anchor.setProvider(provider);
    const program = getProgram(provider);
    const tx = await program.methods
        .initializeGame(new anchor.BN(bigBlind), maxPlayers)
        .accounts({
            authority: (wallet as any).publicKey,
        })
        .rpc();
    return tx;
}

/** Player joins a game */
export async function joinGame(
    wallet: Wallet,
    gamePubkey: PublicKey,
    playerTokenAccount: PublicKey,
    gameTokenAccount: PublicKey,
    buyInAmount: number,
) {
    const provider = getProvider(wallet);
    anchor.setProvider(provider);
    const program = getProgram(provider);
    const tx = await program.methods
        .joinGame(new anchor.BN(buyInAmount))
        .accounts({
            game: gamePubkey,
            player: (wallet as any).publicKey,
            playerTokenAccount,
            gameTokenAccount,
        })
        .rpc();
    return tx;
}

/** Request a shuffle (VRF placeholder) */
export async function requestShuffle(wallet: Wallet, gamePubkey: PublicKey) {
    const provider = getProvider(wallet);
    anchor.setProvider(provider);
    const program = getProgram(provider);
    const tx = await program.methods
        .requestShuffle()
        .accounts({
            game: gamePubkey,
            authority: (wallet as any).publicKey,
        })
        .rpc();
    return tx;
}

/** Distribute the pot to winners */
export async function distributePot(
    wallet: Wallet,
    gamePubkey: PublicKey,
    gameTokenAccount: PublicKey,
    winnerIndices: number[],
) {
    const provider = getProvider(wallet);
    anchor.setProvider(provider);
    const program = getProgram(provider);
    const tx = await program.methods
        .distributePot(winnerIndices)
        .accounts({
            game: gamePubkey,
            authority: (wallet as any).publicKey,
            gameTokenAccount,
        })
        .rpc();
    return tx;
}
